## https://extbrain.tistory.com/60
## DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d')

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
FROM (SELECT *
      FROM MEMBER_PROFILE
      WHERE MONTH(DATE_OF_BIRTH) = 03) AS A
WHERE TLNO IS NOT NULL AND GENDER = "W"
ORDER BY MEMBER_ID ASC