# 아이스크림 가게의 상반기 주문 정보를 담은 FIRST_HALF 테이블
# 아이스크림 성분에 대한 정보를 담은 ICECREAM_INFO 테이블

SELECT T.FLAVOR
FROM (SELECT A.FLAVOR AS FLAVOR, A.TOTAL_ORDER
      FROM FIRST_HALF AS A
      JOIN ICECREAM_INFO AS B
      ON A.FLAVOR = B.FLAVOR
      WHERE B.INGREDIENT_TYPE = "fruit_based"
    ) AS T
WHERE T.TOTAL_ORDER > 3000
ORDER BY T.TOTAL_ORDER DESC